# Generated by Django 6.0.2 on 2026-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamesLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamesWon',
            field=models.IntegerField(default=0),
        ),
    ]
