# Generated by Django 6.0.2 on 2026-02-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_gameslost_profile_gameswon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gamesLost',
        ),
        migrations.AddField(
            model_name='profile',
            name='gamesTotal',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gamesWon',
            field=models.IntegerField(default=5),
        ),
    ]
