# Generated by Django 6.0.2 on 2026-02-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gamesTotal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gamesWon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
