# Generated by Django 6.0.2 on 2026-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_profile_friends_remove_profile_gamestotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamesPlayed',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamesWon',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
