# Generated by Django 6.0.2 on 2026-02-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_gamesplayed_profile_gameswon_profile_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gamesPlayed',
            new_name='gamesTotal',
        ),
    ]
