# Generated by Django 6.0.2 on 2026-03-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_teams_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner_of_the', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(default=1)),
                ('gamemaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Headmaster_of', to='api.profile')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1_of', to='api.teams')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2_of', to='api.teams')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teams')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
