# Generated by Django 6.0.2 on 2026-03-03 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_teams_owner_game_delete_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gameSystem', models.CharField(max_length=30)),
                ('gameTime', models.CharField(max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QueueTeam', to='api.teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QueueUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
