# Generated by Django 6.0.2 on 2026-03-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_queuegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='Teams_of', to='api.teams'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamemaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Headmaster_of', to='api.profile'),
        ),
    ]
