# Generated by Django 6.0.2 on 2026-03-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_game_team1_remove_game_team2_game_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_od', to='api.game'),
        ),
    ]
