# Generated by Django 6.0.2 on 2026-03-12 00:01

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_profile_currentgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameSystem',
            field=models.CharField(default="linux", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gameTime',
            field=models.CharField(default="30m", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='stateEnd',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='stateStart',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
