# Generated by Django 6.0.2 on 2026-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_game_gamesystem_game_gametime_game_stateend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
