# Generated by Django 6.0.2 on 2026-03-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_game_stateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameSystem',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameTime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
